### ISSUE TITLE
Support for other os

### ISSUE THREAD

**Issue by Fandekasp** [vnc-biz/zcs-zmpkg#1]
Hi,

I wish to run openerp & zimbra on other os than Debian (Red hat, Arch linux), but I couldn't find a good way to do so because of this dpkg dependancy.

Would it be difficult to add a more compatible installation process (./configure, make && make install) ?

**Comment by stefansaenger** [comment]
since ArchLinux is not a supported distribution to run zimbra, and all distributions that are supported by zimbra are supported by zmpkg as well, this can be closed.
