### ISSUE TITLE
Zmpkg not possible on Suse Distribution

### ISSUE THREAD

**Issue by xander2k** [vnc-biz/zcs-zmpkg#8]
I've tried several things, but after i while i found a debian paket to use dpkg.

I set the PATH variable and when running the following command
./install.sh /opt/zimbra
dpkg: `update-rc.d' not found on PATH.
dpkg: 1 expected program(s) not found on PATH.
NB: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin.

I found no way to fix this issue, but suse and debian has different rc.d.

Thats not an plattform independent packaging system, and there is no guide how to fix this.

**Comment by stefansaenger** [comment]
try using the latest zmpkg-installer. The problem itself was fixed a while ago, and it was basically a minor installation bug.
